/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite';
import { Route as DashboardRouteImport } from './routes/dashboard';
import { Route as LoginRouteImport } from './routes/login';
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index';
import { Route as DashboardBulletinsRouteImport } from './routes/dashboard.bulletins';
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar';
import { Route as DashboardEtudiantsRouteImport } from './routes/dashboard.etudiants';
import { Route as DashboardExamensRouteImport } from './routes/dashboard.examens';
import { Route as DashboardFormateursRouteImport } from './routes/dashboard.formateurs';
import { Route as DashboardPaiementsRouteImport } from './routes/dashboard.paiements';
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings';
import { Route as DashboardStagesRouteImport } from './routes/dashboard.stages';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardBulletinsRoute = DashboardBulletinsRouteImport.update({
  id: '/bulletins',
  path: '/bulletins',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardEtudiantsRoute = DashboardEtudiantsRouteImport.update({
  id: '/etudiants',
  path: '/etudiants',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardExamensRoute = DashboardExamensRouteImport.update({
  id: '/examens',
  path: '/examens',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardFormateursRoute = DashboardFormateursRouteImport.update({
  id: '/formateurs',
  path: '/formateurs',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardPaiementsRoute = DashboardPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardStagesRoute = DashboardStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => DashboardRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/confidentialite': typeof ConfidentialiteRoute;
  '/dashboard': typeof DashboardRouteWithChildren;
  '/login': typeof LoginRoute;
  '/dashboard/bulletins': typeof DashboardBulletinsRoute;
  '/dashboard/calendar': typeof DashboardCalendarRoute;
  '/dashboard/etudiants': typeof DashboardEtudiantsRoute;
  '/dashboard/examens': typeof DashboardExamensRoute;
  '/dashboard/formateurs': typeof DashboardFormateursRoute;
  '/dashboard/paiements': typeof DashboardPaiementsRoute;
  '/dashboard/settings': typeof DashboardSettingsRoute;
  '/dashboard/stages': typeof DashboardStagesRoute;
  '/dashboard/': typeof DashboardIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/confidentialite': typeof ConfidentialiteRoute;
  '/login': typeof LoginRoute;
  '/dashboard/bulletins': typeof DashboardBulletinsRoute;
  '/dashboard/calendar': typeof DashboardCalendarRoute;
  '/dashboard/etudiants': typeof DashboardEtudiantsRoute;
  '/dashboard/examens': typeof DashboardExamensRoute;
  '/dashboard/formateurs': typeof DashboardFormateursRoute;
  '/dashboard/paiements': typeof DashboardPaiementsRoute;
  '/dashboard/settings': typeof DashboardSettingsRoute;
  '/dashboard/stages': typeof DashboardStagesRoute;
  '/dashboard': typeof DashboardIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/confidentialite': typeof ConfidentialiteRoute;
  '/dashboard': typeof DashboardRouteWithChildren;
  '/login': typeof LoginRoute;
  '/dashboard/bulletins': typeof DashboardBulletinsRoute;
  '/dashboard/calendar': typeof DashboardCalendarRoute;
  '/dashboard/etudiants': typeof DashboardEtudiantsRoute;
  '/dashboard/examens': typeof DashboardExamensRoute;
  '/dashboard/formateurs': typeof DashboardFormateursRoute;
  '/dashboard/paiements': typeof DashboardPaiementsRoute;
  '/dashboard/settings': typeof DashboardSettingsRoute;
  '/dashboard/stages': typeof DashboardStagesRoute;
  '/dashboard/': typeof DashboardIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/confidentialite'
    | '/dashboard'
    | '/login'
    | '/dashboard/bulletins'
    | '/dashboard/calendar'
    | '/dashboard/etudiants'
    | '/dashboard/examens'
    | '/dashboard/formateurs'
    | '/dashboard/paiements'
    | '/dashboard/settings'
    | '/dashboard/stages'
    | '/dashboard/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/confidentialite'
    | '/login'
    | '/dashboard/bulletins'
    | '/dashboard/calendar'
    | '/dashboard/etudiants'
    | '/dashboard/examens'
    | '/dashboard/formateurs'
    | '/dashboard/paiements'
    | '/dashboard/settings'
    | '/dashboard/stages'
    | '/dashboard';
  id:
    | '__root__'
    | '/'
    | '/confidentialite'
    | '/dashboard'
    | '/login'
    | '/dashboard/bulletins'
    | '/dashboard/calendar'
    | '/dashboard/etudiants'
    | '/dashboard/examens'
    | '/dashboard/formateurs'
    | '/dashboard/paiements'
    | '/dashboard/settings'
    | '/dashboard/stages'
    | '/dashboard/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ConfidentialiteRoute: typeof ConfidentialiteRoute;
  DashboardRoute: typeof DashboardRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/confidentialite': {
      id: '/confidentialite';
      path: '/confidentialite';
      fullPath: '/confidentialite';
      preLoaderRoute: typeof ConfidentialiteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard/': {
      id: '/dashboard/';
      path: '/';
      fullPath: '/dashboard/';
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/bulletins': {
      id: '/dashboard/bulletins';
      path: '/bulletins';
      fullPath: '/dashboard/bulletins';
      preLoaderRoute: typeof DashboardBulletinsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/calendar': {
      id: '/dashboard/calendar';
      path: '/calendar';
      fullPath: '/dashboard/calendar';
      preLoaderRoute: typeof DashboardCalendarRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/etudiants': {
      id: '/dashboard/etudiants';
      path: '/etudiants';
      fullPath: '/dashboard/etudiants';
      preLoaderRoute: typeof DashboardEtudiantsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/examens': {
      id: '/dashboard/examens';
      path: '/examens';
      fullPath: '/dashboard/examens';
      preLoaderRoute: typeof DashboardExamensRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/formateurs': {
      id: '/dashboard/formateurs';
      path: '/formateurs';
      fullPath: '/dashboard/formateurs';
      preLoaderRoute: typeof DashboardFormateursRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/paiements': {
      id: '/dashboard/paiements';
      path: '/paiements';
      fullPath: '/dashboard/paiements';
      preLoaderRoute: typeof DashboardPaiementsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/settings': {
      id: '/dashboard/settings';
      path: '/settings';
      fullPath: '/dashboard/settings';
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/stages': {
      id: '/dashboard/stages';
      path: '/stages';
      fullPath: '/dashboard/stages';
      preLoaderRoute: typeof DashboardStagesRouteImport;
      parentRoute: typeof DashboardRoute;
    };
  }
}

interface DashboardRouteChildren {
  DashboardBulletinsRoute: typeof DashboardBulletinsRoute;
  DashboardCalendarRoute: typeof DashboardCalendarRoute;
  DashboardEtudiantsRoute: typeof DashboardEtudiantsRoute;
  DashboardExamensRoute: typeof DashboardExamensRoute;
  DashboardFormateursRoute: typeof DashboardFormateursRoute;
  DashboardPaiementsRoute: typeof DashboardPaiementsRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardStagesRoute: typeof DashboardStagesRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBulletinsRoute: DashboardBulletinsRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardEtudiantsRoute: DashboardEtudiantsRoute,
  DashboardExamensRoute: DashboardExamensRoute,
  DashboardFormateursRoute: DashboardFormateursRoute,
  DashboardPaiementsRoute: DashboardPaiementsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStagesRoute: DashboardStagesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
