export interface ActionParam {
  name: string;
  type: "string" | "number" | "boolean" | "array" | "object";
  description: string;
  required?: boolean;
  enum?: string[];
}

export interface ActionDefinition {
  name: string;
  description: string;
  method: "GET" | "POST" | "PUT" | "DELETE";
  path: string;
  category: string;
  requiredRoles: string[];
  params: ActionParam[];
}

const ACTIONS: ActionDefinition[] = [
  // ── Dashboard ──────────────────────────────────────────────────────
  {
    name: "get_dashboard_stats",
    description: "Obtenir les statistiques principales du tableau de bord (total inscrits, formateurs actifs, taux de réussite, total à recouvrer)",
    method: "GET",
    path: "/api/dashboard/stats",
    category: "Tableau de bord",
    requiredRoles: [],
    params: [],
  },
  {
    name: "get_financier",
    description: "Obtenir le récapitulatif financier (encaissements, en attente, impayés, retard, taux de recouvrement)",
    method: "GET",
    path: "/api/dashboard/financier",
    category: "Tableau de bord",
    requiredRoles: [],
    params: [],
  },
  {
    name: "get_etudiants_a_risque",
    description: "Lister les étudiants en risque (moyenne < 10 ou abandon)",
    method: "GET",
    path: "/api/dashboard/etudiants-a-risque",
    category: "Tableau de bord",
    requiredRoles: [],
    params: [],
  },
  {
    name: "get_a_relancer",
    description: "Lister les étudiants à relancer pour paiement",
    method: "GET",
    path: "/api/dashboard/a-relancer",
    category: "Tableau de bord",
    requiredRoles: [],
    params: [],
  },
  {
    name: "get_a_traiter",
    description: "Obtenir le nombre d'éléments à traiter (examens à venir, bulletins à publier, stages à valider)",
    method: "GET",
    path: "/api/dashboard/a-traiter",
    category: "Tableau de bord",
    requiredRoles: [],
    params: [],
  },
  {
    name: "get_activities",
    description: "Obtenir le fil d'activités récentes (paiements, inscriptions, etc.)",
    method: "GET",
    path: "/api/dashboard/activities",
    category: "Tableau de bord",
    requiredRoles: [],
    params: [],
  },

  // ── Students ───────────────────────────────────────────────────────
  {
    name: "list_etudiants",
    description: "Rechercher et lister les étudiants (filtres: search, filiere, niveau, statut)",
    method: "GET",
    path: "/api/etudiants",
    category: "Étudiants",
    requiredRoles: [],
    params: [
      { name: "search", type: "string", description: "Recherche par prénom, nom, CNE ou matricule" },
      { name: "filiere", type: "string", description: "Filtrer par filière" },
      { name: "niveau", type: "string", description: "Filtrer par niveau (S1, S2, S3, S4, S5, S6)" },
      { name: "statut", type: "string", description: "Filtrer par statut (inscrit, diplome, abandon, suspendu)", enum: ["inscrit", "diplome", "abandon", "suspendu"] },
    ],
  },
  {
    name: "get_etudiant",
    description: "Obtenir les détails d'un étudiant (notes, historique paiements, stage en cours)",
    method: "GET",
    path: "/api/etudiants/:id",
    category: "Étudiants",
    requiredRoles: [],
    params: [
      { name: "id", type: "string", description: "ID de l'étudiant", required: true },
    ],
  },
  {
    name: "create_etudiant",
    description: "Créer un nouvel étudiant",
    method: "POST",
    path: "/api/etudiants",
    category: "Étudiants",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "prenom", type: "string", description: "Prénom de l'étudiant", required: true },
      { name: "nom", type: "string", description: "Nom de l'étudiant", required: true },
      { name: "filiere", type: "string", description: "Filière", required: true },
      { name: "niveau", type: "string", description: "Niveau (S1-S6)", required: true },
      { name: "cne", type: "string", description: "CNE" },
      { name: "matricule", type: "string", description: "Matricule" },
      { name: "annee", type: "string", description: "Année universitaire" },
      { name: "groupe", type: "string", description: "Groupe" },
      { name: "statut", type: "string", description: "Statut", enum: ["inscrit", "diplome", "abandon", "suspendu"] },
      { name: "telephone", type: "string", description: "Téléphone" },
      { name: "email", type: "string", description: "Email" },
      { name: "dateNaissance", type: "string", description: "Date de naissance (YYYY-MM-DD)" },
      { name: "ville", type: "string", description: "Ville" },
      { name: "fraisMensuels", type: "number", description: "Frais mensuels" },
    ],
  },
  {
    name: "update_etudiant",
    description: "Modifier un étudiant existant",
    method: "PUT",
    path: "/api/etudiants/:id",
    category: "Étudiants",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID de l'étudiant", required: true },
      { name: "prenom", type: "string", description: "Prénom" },
      { name: "nom", type: "string", description: "Nom" },
      { name: "filiere", type: "string", description: "Filière" },
      { name: "niveau", type: "string", description: "Niveau" },
      { name: "statut", type: "string", description: "Statut", enum: ["inscrit", "diplome", "abandon", "suspendu"] },
      { name: "telephone", type: "string", description: "Téléphone" },
      { name: "email", type: "string", description: "Email" },
      { name: "fraisMensuels", type: "number", description: "Frais mensuels" },
    ],
  },
  {
    name: "delete_etudiant",
    description: "Supprimer un étudiant et ses données associées (bulletins, stages)",
    method: "DELETE",
    path: "/api/etudiants/:id",
    category: "Étudiants",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID de l'étudiant", required: true },
    ],
  },

  // ── Teachers ───────────────────────────────────────────────────────
  {
    name: "list_formateurs",
    description: "Rechercher et lister les formateurs/enseignants",
    method: "GET",
    path: "/api/formateurs",
    category: "Formateurs",
    requiredRoles: [],
    params: [
      { name: "search", type: "string", description: "Recherche par prénom, nom, matricule ou CIN" },
      { name: "departement", type: "string", description: "Filtrer par département" },
      { name: "grade", type: "string", description: "Filtrer par grade" },
    ],
  },
  {
    name: "create_formateur",
    description: "Ajouter un nouveau formateur",
    method: "POST",
    path: "/api/formateurs",
    category: "Formateurs",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "prenom", type: "string", description: "Prénom", required: true },
      { name: "nom", type: "string", description: "Nom", required: true },
      { name: "matricule", type: "string", description: "Matricule" },
      { name: "cin", type: "string", description: "CIN" },
      { name: "grade", type: "string", description: "Grade", enum: ["vacataire", "permanent", "invite"] },
      { name: "departement", type: "string", description: "Département" },
      { name: "modules", type: "array", description: "Modules enseignés (tableau de strings)" },
      { name: "groupes", type: "array", description: "Groupes (tableau de strings)" },
      { name: "statut", type: "string", description: "Statut", enum: ["permanent", "en_conge"] },
      { name: "telephone", type: "string", description: "Téléphone" },
      { name: "email", type: "string", description: "Email" },
    ],
  },
  {
    name: "update_formateur",
    description: "Modifier un formateur",
    method: "PUT",
    path: "/api/formateurs/:id",
    category: "Formateurs",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID du formateur", required: true },
      { name: "prenom", type: "string", description: "Prénom" },
      { name: "nom", type: "string", description: "Nom" },
      { name: "grade", type: "string", description: "Grade" },
      { name: "modules", type: "array", description: "Modules enseignés" },
      { name: "telephone", type: "string", description: "Téléphone" },
      { name: "email", type: "string", description: "Email" },
    ],
  },
  {
    name: "delete_formateur",
    description: "Supprimer un formateur",
    method: "DELETE",
    path: "/api/formateurs/:id",
    category: "Formateurs",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID du formateur", required: true },
    ],
  },

  // ── Exams ──────────────────────────────────────────────────────────
  {
    name: "list_examens",
    description: "Rechercher et lister les examens",
    method: "GET",
    path: "/api/examens",
    category: "Examens",
    requiredRoles: [],
    params: [
      { name: "filiere", type: "string", description: "Filtrer par filière" },
      { name: "niveau", type: "string", description: "Filtrer par niveau" },
      { name: "statut", type: "string", description: "Filtrer par statut", enum: ["planifie", "en_cours", "notes_saisies"] },
      { name: "module", type: "string", description: "Filtrer par module" },
    ],
  },
  {
    name: "create_examen",
    description: "Planifier un nouvel examen",
    method: "POST",
    path: "/api/examens",
    category: "Examens",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "module", type: "string", description: "Module", required: true },
      { name: "filiere", type: "string", description: "Filière", required: true },
      { name: "niveau", type: "string", description: "Niveau", required: true },
      { name: "type", type: "string", description: "Type d'examen", required: true, enum: ["Theorique", "Pratique", "Clinique"] },
      { name: "date", type: "string", description: "Date (YYYY-MM-DD)", required: true },
      { name: "heure", type: "string", description: "Heure (HH:MM)" },
      { name: "salle", type: "string", description: "Salle" },
      { name: "surveillants", type: "array", description: "Surveillants (tableau de noms)" },
      { name: "groupe", type: "string", description: "Groupe" },
      { name: "duree", type: "number", description: "Durée en minutes" },
      { name: "composante", type: "string", description: "Composante", enum: ["Theorique", "Pratique", "Clinique"] },
      { name: "description", type: "string", description: "Description" },
    ],
  },
  {
    name: "update_examen",
    description: "Modifier un examen",
    method: "PUT",
    path: "/api/examens/:id",
    category: "Examens",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID de l'examen", required: true },
      { name: "module", type: "string", description: "Module" },
      { name: "date", type: "string", description: "Date (YYYY-MM-DD)" },
      { name: "heure", type: "string", description: "Heure" },
      { name: "salle", type: "string", description: "Salle" },
      { name: "statut", type: "string", description: "Statut" },
    ],
  },
  {
    name: "delete_examen",
    description: "Supprimer un examen",
    method: "DELETE",
    path: "/api/examens/:id",
    category: "Examens",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID de l'examen", required: true },
    ],
  },
  {
    name: "save_notes_examen",
    description: "Saisir les notes d'un examen pour plusieurs étudiants",
    method: "POST",
    path: "/api/examens/:id/notes",
    category: "Examens",
    requiredRoles: ["directeur", "enseignant"],
    params: [
      { name: "id", type: "string", description: "ID de l'examen", required: true },
      { name: "saisies", type: "array", description: "Tableau des notes: [{ etudiantId, theorique?, pratique? }]", required: true },
    ],
  },

  // ── Report Cards ───────────────────────────────────────────────────
  {
    name: "list_bulletins",
    description: "Rechercher et lister les bulletins de notes",
    method: "GET",
    path: "/api/bulletins",
    category: "Bulletins",
    requiredRoles: [],
    params: [
      { name: "filiere", type: "string", description: "Filtrer par filière" },
      { name: "niveau", type: "string", description: "Filtrer par niveau" },
      { name: "statut", type: "string", description: "Filtrer par statut", enum: ["genere", "valide", "publie"] },
      { name: "session", type: "string", description: "Filtrer par session (normale, rattrapage)" },
      { name: "search", type: "string", description: "Recherche par prénom, nom ou CNE" },
    ],
  },
  {
    name: "create_bulletin",
    description: "Générer un bulletin pour un étudiant",
    method: "POST",
    path: "/api/bulletins",
    category: "Bulletins",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "etudiantId", type: "string", description: "ID de l'étudiant", required: true },
      { name: "session", type: "string", description: "Session (normale, rattrapage)" },
      { name: "moyenne", type: "number", description: "Moyenne générale" },
      { name: "mention", type: "string", description: "Mention" },
      { name: "decision", type: "string", description: "Décision (Admis, Rattrapage, Ajourné)" },
    ],
  },
  {
    name: "update_bulletin",
    description: "Modifier un bulletin",
    method: "PUT",
    path: "/api/bulletins/:id",
    category: "Bulletins",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID du bulletin", required: true },
      { name: "moyenne", type: "number", description: "Moyenne" },
      { name: "mention", type: "string", description: "Mention" },
      { name: "decision", type: "string", description: "Décision" },
      { name: "statut", type: "string", description: "Statut", enum: ["genere", "valide", "publie"] },
    ],
  },
  {
    name: "delete_bulletin",
    description: "Supprimer un bulletin",
    method: "DELETE",
    path: "/api/bulletins/:id",
    category: "Bulletins",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID du bulletin", required: true },
    ],
  },
  {
    name: "publier_bulletin",
    description: "Publier un bulletin (le rend visible pour l'étudiant)",
    method: "POST",
    path: "/api/bulletins/:id/publier",
    category: "Bulletins",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID du bulletin", required: true },
    ],
  },
  {
    name: "publier_tous_bulletins",
    description: "Publier tous les bulletins en une seule action",
    method: "POST",
    path: "/api/bulletins/publier-tout",
    category: "Bulletins",
    requiredRoles: ["directeur", "responsable"],
    params: [],
  },

  // ── Internships ────────────────────────────────────────────────────
  {
    name: "list_stages",
    description: "Rechercher et lister les stages",
    method: "GET",
    path: "/api/stages",
    category: "Stages",
    requiredRoles: [],
    params: [
      { name: "filiere", type: "string", description: "Filtrer par filière" },
      { name: "niveau", type: "string", description: "Filtrer par niveau" },
      { name: "statut", type: "string", description: "Filtrer par statut (recherche, en_cours, convention_signee, soutenance, valide)", enum: ["recherche", "en_cours", "convention_signee", "soutenance", "valide"] },
      { name: "search", type: "string", description: "Recherche par prénom, nom, CNE ou structure" },
    ],
  },
  {
    name: "create_stage",
    description: "Créer un stage pour un étudiant",
    method: "POST",
    path: "/api/stages",
    category: "Stages",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "etudiantId", type: "string", description: "ID de l'étudiant", required: true },
      { name: "structure", type: "string", description: "Structure d'accueil" },
      { name: "service", type: "string", description: "Service" },
      { name: "encadrantClinique", type: "string", description: "Encadrant clinique" },
      { name: "tuteurAcademique", type: "string", description: "Tuteur académique" },
      { name: "debut", type: "string", description: "Date de début (YYYY-MM-DD)" },
      { name: "fin", type: "string", description: "Date de fin (YYYY-MM-DD)" },
      { name: "statut", type: "string", description: "Statut", enum: ["recherche", "en_cours", "convention_signee", "soutenance", "valide"] },
    ],
  },
  {
    name: "update_stage",
    description: "Modifier un stage",
    method: "PUT",
    path: "/api/stages/:id",
    category: "Stages",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID du stage", required: true },
      { name: "structure", type: "string", description: "Structure d'accueil" },
      { name: "statut", type: "string", description: "Statut" },
      { name: "noteSoutenance", type: "number", description: "Note de soutenance (0-20)" },
    ],
  },
  {
    name: "delete_stage",
    description: "Supprimer un stage",
    method: "DELETE",
    path: "/api/stages/:id",
    category: "Stages",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID du stage", required: true },
    ],
  },
  {
    name: "valider_stage",
    description: "Valider un stage (passe le statut à 'valide')",
    method: "POST",
    path: "/api/stages/:id/valider",
    category: "Stages",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID du stage", required: true },
    ],
  },

  // ── Payments ───────────────────────────────────────────────────────
  {
    name: "list_paiements",
    description: "Lister les paiements des étudiants",
    method: "GET",
    path: "/api/monthly-payments",
    category: "Paiements",
    requiredRoles: [],
    params: [
      { name: "etudiantId", type: "string", description: "Filtrer par étudiant" },
    ],
  },
  {
    name: "create_paiement",
    description: "Enregistrer un paiement pour un étudiant",
    method: "POST",
    path: "/api/monthly-payments",
    category: "Paiements",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "etudiantId", type: "string", description: "ID de l'étudiant", required: true },
      { name: "montant", type: "number", description: "Montant du paiement", required: true },
      { name: "mode", type: "string", description: "Mode de paiement", enum: ["Especes", "Virement", "Carte", "Cheque"] },
      { name: "periode", type: "string", description: "Période concernée" },
      { name: "mois", type: "string", description: "Mois concerné" },
      { name: "date", type: "string", description: "Date du paiement (YYYY-MM-DD)" },
    ],
  },
  {
    name: "get_paiement_stats",
    description: "Obtenir les statistiques globales des paiements",
    method: "GET",
    path: "/api/monthly-payments/stats",
    category: "Paiements",
    requiredRoles: [],
    params: [],
  },

  // ── Grades ─────────────────────────────────────────────────────────
  {
    name: "create_note",
    description: "Ajouter ou modifier une note pour un étudiant dans un module (met à jour la moyenne automatiquement)",
    method: "POST",
    path: "/api/notes",
    category: "Notes",
    requiredRoles: ["directeur", "enseignant", "responsable"],
    params: [
      { name: "etudiantId", type: "string", description: "ID de l'étudiant", required: true },
      { name: "module", type: "string", description: "Nom du module", required: true },
      { name: "note", type: "number", description: "Note (0-20)", required: true },
      { name: "coef", type: "number", description: "Coefficient (défaut: 3)" },
      { name: "credits", type: "number", description: "Crédits (défaut: 6)" },
      { name: "examen", type: "string", description: "Examen associé" },
    ],
  },
  {
    name: "delete_note",
    description: "Supprimer une note (la moyenne est recalculée automatiquement)",
    method: "DELETE",
    path: "/api/notes/:id",
    category: "Notes",
    requiredRoles: ["directeur", "enseignant", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID de la note", required: true },
    ],
  },

  // ── Classes ────────────────────────────────────────────────────────
  {
    name: "list_seances",
    description: "Rechercher et lister les séances de cours",
    method: "GET",
    path: "/api/seances",
    category: "Séances",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "start", type: "string", description: "Date début (YYYY-MM-DD)" },
      { name: "end", type: "string", description: "Date fin (YYYY-MM-DD)" },
      { name: "professeurId", type: "string", description: "Filtrer par professeur" },
      { name: "date", type: "string", description: "Filtrer par date exacte (YYYY-MM-DD)" },
    ],
  },
  {
    name: "create_seance",
    description: "Créer une séance de cours",
    method: "POST",
    path: "/api/seances",
    category: "Séances",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "date", type: "string", description: "Date (YYYY-MM-DD)", required: true },
      { name: "module", type: "string", description: "Module", required: true },
      { name: "filiere", type: "string", description: "Filière", required: true },
      { name: "debut", type: "string", description: "Heure début (HH:MM)" },
      { name: "fin", type: "string", description: "Heure fin (HH:MM)" },
      { name: "professeurId", type: "string", description: "ID du professeur" },
      { name: "salle", type: "string", description: "Salle" },
      { name: "groupe", type: "string", description: "Groupe" },
      { name: "type", type: "string", description: "Type", enum: ["cours", "td", "tp", "examen", "stage", "soutenance"] },
    ],
  },
  {
    name: "create_seances_bulk",
    description: "Créer plusieurs séances en une seule opération (max 100)",
    method: "POST",
    path: "/api/seances/bulk",
    category: "Séances",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "seances", type: "array", description: "Tableau de séances à créer", required: true },
    ],
  },
  {
    name: "update_seance",
    description: "Modifier une séance",
    method: "PUT",
    path: "/api/seances/:id",
    category: "Séances",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID de la séance", required: true },
      { name: "date", type: "string", description: "Date" },
      { name: "debut", type: "string", description: "Heure début" },
      { name: "fin", type: "string", description: "Heure fin" },
      { name: "module", type: "string", description: "Module" },
      { name: "salle", type: "string", description: "Salle" },
      { name: "statut", type: "string", description: "Statut", enum: ["planifie", "en_cours", "termine", "annule"] },
    ],
  },
  {
    name: "delete_seance",
    description: "Supprimer une séance",
    method: "DELETE",
    path: "/api/seances/:id",
    category: "Séances",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID de la séance", required: true },
    ],
  },

  // ── Attendance ─────────────────────────────────────────────────────
  {
    name: "open_attendance_session",
    description: "Ouvrir une session d'appel pour une séance",
    method: "POST",
    path: "/api/attendance/session/open",
    category: "Présences",
    requiredRoles: ["directeur", "responsable", "enseignant"],
    params: [
      { name: "seanceId", type: "string", description: "ID de la séance", required: true },
    ],
  },
  {
    name: "close_attendance_session",
    description: "Fermer une session d'appel",
    method: "POST",
    path: "/api/attendance/session/:id/close",
    category: "Présences",
    requiredRoles: ["directeur", "responsable", "enseignant"],
    params: [
      { name: "id", type: "string", description: "ID de la session d'appel", required: true },
    ],
  },
  {
    name: "submit_attendance",
    description: "Soumettre les présences pour une séance",
    method: "POST",
    path: "/api/attendance/bulk",
    category: "Présences",
    requiredRoles: ["directeur", "responsable", "enseignant"],
    params: [
      { name: "seanceId", type: "string", description: "ID de la séance", required: true },
      { name: "entries", type: "array", description: "Tableau des présences: [{ etudiantId, present, justifie? }]", required: true },
    ],
  },
  {
    name: "get_attendance_summary",
    description: "Obtenir le résumé des présences pour une séance",
    method: "GET",
    path: "/api/attendance/summary/seance/:seanceId",
    category: "Présences",
    requiredRoles: [],
    params: [
      { name: "seanceId", type: "string", description: "ID de la séance", required: true },
    ],
  },

  // ── Settings ───────────────────────────────────────────────────────
  {
    name: "get_settings",
    description: "Obtenir tous les paramètres de l'application",
    method: "GET",
    path: "/api/settings",
    category: "Paramètres",
    requiredRoles: [],
    params: [],
  },
  {
    name: "update_setting",
    description: "Mettre à jour un paramètre",
    method: "PUT",
    path: "/api/settings/:key",
    category: "Paramètres",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "key", type: "string", description: "Clé du paramètre", required: true },
      { name: "value", type: "object", description: "Valeur du paramètre", required: true },
    ],
  },
  {
    name: "get_levels",
    description: "Lister les niveaux académiques",
    method: "GET",
    path: "/api/settings/levels",
    category: "Paramètres",
    requiredRoles: [],
    params: [],
  },
  {
    name: "create_level",
    description: "Créer un niveau académique",
    method: "POST",
    path: "/api/settings/levels",
    category: "Paramètres",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "name", type: "string", description: "Nom du niveau", required: true },
      { name: "cycle", type: "string", description: "Cycle" },
      { name: "monthlyFee", type: "number", description: "Frais mensuels" },
    ],
  },
  {
    name: "delete_level",
    description: "Supprimer un niveau académique",
    method: "DELETE",
    path: "/api/settings/levels/:id",
    category: "Paramètres",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID du niveau", required: true },
    ],
  },
  {
    name: "get_filieres",
    description: "Lister les filières disponibles",
    method: "GET",
    path: "/api/settings/filieres",
    category: "Paramètres",
    requiredRoles: [],
    params: [],
  },
  {
    name: "create_filiere",
    description: "Ajouter une filière",
    method: "POST",
    path: "/api/settings/filieres",
    category: "Paramètres",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "nom", type: "string", description: "Nom de la filière", required: true },
    ],
  },
  {
    name: "delete_filiere",
    description: "Supprimer une filière",
    method: "DELETE",
    path: "/api/settings/filieres/:nom",
    category: "Paramètres",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "nom", type: "string", description: "Nom de la filière", required: true },
    ],
  },

  // ── Events ─────────────────────────────────────────────────────────
  {
    name: "list_events",
    description: "Lister les événements du calendrier",
    method: "GET",
    path: "/api/events",
    category: "Événements",
    requiredRoles: [],
    params: [
      { name: "start", type: "string", description: "Date début (YYYY-MM-DD)" },
      { name: "end", type: "string", description: "Date fin (YYYY-MM-DD)" },
      { name: "type", type: "string", description: "Type d'événement", enum: ["event", "meeting", "deadline", "reminder", "task"] },
    ],
  },
  {
    name: "create_event",
    description: "Créer un événement dans le calendrier",
    method: "POST",
    path: "/api/events",
    category: "Événements",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "title", type: "string", description: "Titre de l'événement", required: true },
      { name: "date", type: "string", description: "Date (YYYY-MM-DD)", required: true },
      { name: "startTime", type: "string", description: "Heure début (HH:MM)" },
      { name: "endTime", type: "string", description: "Heure fin (HH:MM)" },
      { name: "type", type: "string", description: "Type", enum: ["event", "meeting", "deadline", "reminder", "task"] },
      { name: "description", type: "string", description: "Description" },
      { name: "location", type: "string", description: "Lieu" },
    ],
  },
  {
    name: "delete_event",
    description: "Supprimer un événement",
    method: "DELETE",
    path: "/api/events/:id",
    category: "Événements",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID de l'événement", required: true },
    ],
  },

  // ── Users & Roles ──────────────────────────────────────────────────
  {
    name: "list_users",
    description: "Lister les utilisateurs du système",
    method: "GET",
    path: "/api/auth/users",
    category: "Utilisateurs",
    requiredRoles: [],
    params: [],
  },
  {
    name: "create_user",
    description: "Créer un nouvel utilisateur",
    method: "POST",
    path: "/api/auth/register",
    category: "Utilisateurs",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "email", type: "string", description: "Email", required: true },
      { name: "password", type: "string", description: "Mot de passe (min 6 caractères)", required: true },
      { name: "name", type: "string", description: "Nom complet", required: true },
      { name: "role", type: "string", description: "Rôle", enum: ["admin", "superadmin", "directeur", "enseignant", "responsable"] },
    ],
  },
  {
    name: "update_user",
    description: "Modifier un utilisateur",
    method: "PUT",
    path: "/api/auth/users/:id",
    category: "Utilisateurs",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID de l'utilisateur", required: true },
      { name: "name", type: "string", description: "Nom" },
      { name: "password", type: "string", description: "Nouveau mot de passe" },
    ],
  },
  {
    name: "delete_user",
    description: "Supprimer un utilisateur",
    method: "DELETE",
    path: "/api/auth/users/:id",
    category: "Utilisateurs",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "id", type: "string", description: "ID de l'utilisateur", required: true },
    ],
  },
  {
    name: "assign_user_role",
    description: "Changer le rôle d'un utilisateur",
    method: "PUT",
    path: "/api/auth/users/:id/role",
    category: "Utilisateurs",
    requiredRoles: ["directeur", "superadmin"],
    params: [
      { name: "id", type: "string", description: "ID de l'utilisateur", required: true },
      { name: "role", type: "string", description: "Nouveau rôle", required: true, enum: ["admin", "superadmin", "directeur", "enseignant", "responsable"] },
    ],
  },
  {
    name: "list_roles",
    description: "Lister les rôles disponibles",
    method: "GET",
    path: "/api/roles",
    category: "Rôles",
    requiredRoles: ["directeur", "superadmin"],
    params: [],
  },
  {
    name: "create_role",
    description: "Créer un rôle personnalisé",
    method: "POST",
    path: "/api/roles",
    category: "Rôles",
    requiredRoles: ["directeur", "superadmin"],
    params: [
      { name: "name", type: "string", description: "Nom du rôle", required: true },
      { name: "description", type: "string", description: "Description" },
      { name: "permissions", type: "array", description: "Permissions (tableau de strings)" },
    ],
  },
  {
    name: "delete_role",
    description: "Supprimer un rôle (sauf les rôles système)",
    method: "DELETE",
    path: "/api/roles/:id",
    category: "Rôles",
    requiredRoles: ["directeur", "superadmin"],
    params: [
      { name: "id", type: "string", description: "ID du rôle", required: true },
    ],
  },

  // ── Notifications ──────────────────────────────────────────────────
  {
    name: "list_notifications",
    description: "Lister les notifications",
    method: "GET",
    path: "/api/notifications",
    category: "Notifications",
    requiredRoles: [],
    params: [
      { name: "unreadOnly", type: "string", description: "true pour les non lues seulement" },
    ],
  },
  {
    name: "create_notification",
    description: "Créer une notification",
    method: "POST",
    path: "/api/notifications",
    category: "Notifications",
    requiredRoles: ["directeur", "superadmin"],
    params: [
      { name: "title", type: "string", description: "Titre", required: true },
      { name: "message", type: "string", description: "Message" },
      { name: "type", type: "string", description: "Type", enum: ["info", "warning", "success", "error"] },
      { name: "userId", type: "string", description: "Cibler un utilisateur spécifique" },
    ],
  },

  // ── Reminders ──────────────────────────────────────────────────────
  {
    name: "list_reminders",
    description: "Lister les rappels",
    method: "GET",
    path: "/api/reminders",
    category: "Rappels",
    requiredRoles: [],
    params: [],
  },
  {
    name: "create_reminder",
    description: "Créer un rappel",
    method: "POST",
    path: "/api/reminders",
    category: "Rappels",
    requiredRoles: ["directeur", "responsable"],
    params: [
      { name: "title", type: "string", description: "Titre", required: true },
      { name: "remindAt", type: "string", description: "Date et heure du rappel (ISO)", required: true },
      { name: "message", type: "string", description: "Message" },
      { name: "method", type: "string", description: "Méthode", enum: ["in_app", "email"] },
    ],
  },

  // ── Teacher ────────────────────────────────────────────────────────
  {
    name: "get_teacher_dashboard",
    description: "Obtenir le tableau de bord enseignant (séances du jour, examens, étudiants)",
    method: "GET",
    path: "/api/teacher/dashboard",
    category: "Enseignant",
    requiredRoles: [],
    params: [],
  },

  // ── Calendar ───────────────────────────────────────────────────────
  {
    name: "get_calendar_feed",
    description: "Obtenir le flux complet du calendrier (événements, congés, vacances, examens)",
    method: "GET",
    path: "/api/events/feed",
    category: "Calendrier",
    requiredRoles: [],
    params: [
      { name: "start", type: "string", description: "Date début (YYYY-MM-DD)" },
      { name: "end", type: "string", description: "Date fin (YYYY-MM-DD)" },
    ],
  },
];

export default ACTIONS;

export function getToolDefinitions() {
  return ACTIONS.map((a) => ({
    type: "function" as const,
    function: {
      name: a.name,
      description: `${a.description}\nMéthode: ${a.method} ${a.path}\nCatégorie: ${a.category}`,
      parameters: {
        type: "object",
        properties: Object.fromEntries(
          a.params.map((p) => [
            p.name,
            {
              type: p.type === "array" ? "array" : p.type === "object" ? "object" : p.type,
              description: p.description + (p.enum ? ` (valeurs possibles: ${p.enum.join(", ")})` : ""),
              ...(p.enum ? { enum: p.enum } : {}),
              ...(p.type === "array" ? { items: { type: "object" } } : {}),
            },
          ]),
        ),
        required: a.params.filter((p) => p.required).map((p) => p.name),
      },
    },
    _meta: {
      method: a.method,
      path: a.path,
      category: a.category,
      requiredRoles: a.requiredRoles,
    },
  }));
}
